### ISSUE TITLE
generate.sh can't overwrite files on WSL

### ISSUE THREAD

**Issue by mathw** [DrHenchman/uhc-pack#44] opened 2020-07-05 09:43 UTC
Because it uses `trash` to delete the target file with --overwrite enabled, which is a macOS-only utility, the overwrite option can't be used on WSL (or, presumably, Linux).

**Comment by DrHenchman** [comment] 2020-07-05 10:28
Duplicate of #23

**Closed as completed by DrHenchman** 2020-07-05 10:28 UTC
Labels: duplicate
